from mudpuppy_core import Event as Event, InputLine as InputLine, SessionInfo as SessionInfo

class History:
    session: SessionInfo
    lines: list[InputLine]
    max_lines: int
    cursor_pos: int | None
    def __init__(self, session: SessionInfo, max_lines: int = 1000) -> None: ...
    def reset_cursor(self) -> None: ...
    def add(self, line: InputLine): ...
    def next(self) -> InputLine | None: ...
    def prev(self) -> InputLine | None: ...

def get_history(session_id: int) -> History | None: ...
async def input_sent(event: Event): ...
async def shortcut(event: Event): ...
async def setup(event: Event): ...

history: dict[int, History]
