# Uncomment and edit the [[muds]] sections to configure the MUD list available in the client
# The configuration is automatically reloaded when you save.

# [[muds]]
# name = "DuneMUD (TLS)"
# host = "dunemud.net"
# port = 6788
# tls = "Enabled"
# echo_input = true
# no_line_wrap = false

# [[muds]]
# name = "DunemUD (Telnet)"
# host = "dunemud.net"
# port = 6789
# tls = "Disabled"

# Uncomment to enable mouse mode. This may interfere with normal text selection for copy/pasting
# and may not work in all terminals. Requires restarting Mudpuppy to change.
# mouse_enabled = true

# Uncomment to enable scrolling buffer history with the mouse wheel. Requires mouse_enabled = true.
# mouse_scroll = true

[[binding]]
mode = "mudlist"
keys = "up"
action = "mudlistprev"

[[binding]]
mode = "mudlist"
keys = "down"
action = "mudlistnext"

[[binding]]
mode = "mudlist"
keys = "enter"
action = "mudlistconnect"

[[binding]]
mode = "mudlist"
keys = "ctrl-p"
action = "tabprev"

[[binding]]
mode = "mudlist"
keys = "ctrl-n"
action = "tabnext"

[[binding]]
mode = "mudlist"
keys = "q"
action = "quit"

[[binding]]
mode = "mudlist"
keys = "x"
action = "quit"

[[binding]]
mode = "mudlist"
keys = "ctrl-d"
action = "quit"

[[binding]]
mode = "mudlist"
keys = "ctrl-c"
action = "quit"

[[binding]]
mode = "mudlist"
keys = "ctrl-x"
action = "quit"

[[binding]]
keys = "ctrl-p"
action = "tabprev"

[[binding]]
keys = "ctrl-n"
action = "tabnext"

[[binding]]
keys = "alt-p"
action = "tabswapleft"

[[binding]]
keys = "alt-n"
action = "tabswapright"

[[binding]]
keys = "ctrl-d"
action = "quit"

[[binding]]
keys = "ctrl-c"
action = "quit"

[[binding]]
keys = "ctrl-q"
action = "quit"

[[binding]]
keys = "ctrl-x"
action = "tabclose"

[[binding]]
keys = "f2"
action = "toggleinputecho"

[[binding]]
keys = "f3"
action = "togglelinewrap"

[[binding]]
keys = "f8"
action = "ToggleMouseMode"

[[binding]]
keys = "up"
action = "historyprevious"

[[binding]]
keys = "down"
action = "historynext"

[[binding]]
keys = "pageup"
action = "scrollup"

[[binding]]
keys = "pagedown"
action = "scrolldown"

[[binding]]
keys = "shift-home"
action = "scrolltop"

[[binding]]
keys = "shift-end"
action = "scrollbottom"
